# Generated by Django 6.1.1 on 2026-10-04 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CHARGEBACK', 'Chargeback')], default='INITIATED', max_length=50)),
                ('gateway_used', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway_txn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('fraud_score', models.FloatField(blank=True, null=True)),
                ('fraud_action', models.CharField(blank=True, choices=[('ALLOWED', 'Allowed'), ('FLAGGED', 'Flagged'), ('BLOCKED', 'Blocked')], max_length=20, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
