# Generated by Django 6.1.1 on 2026-10-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization_id'], name='transaction_organiz_435692_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_71abbb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['gateway_used'], name='transaction_gateway_3d8ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['initiated_at'], name='transaction_initiat_f1e6f3_idx'),
        ),
    ]
