# Generated by Django 6.1.1 on 2026-10-04 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_response_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('health_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='gateways.gatewayconfig')),
            ],
        ),
    ]
