# Generated by Django 6.1.1 on 2026-10-05 00:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('settlement_file_id', models.UUIDField()),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gateway_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISMATCH', 'Mismatch'), ('MISSING', 'Missing'), ('EXTRA', 'Extra')], max_length=20)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
