# Generated by Django 6.1.1 on 2026-10-04 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField()),
                ('score', models.FloatField()),
                ('velocity_score', models.FloatField(blank=True, null=True)),
                ('geo_score', models.FloatField(blank=True, null=True)),
                ('device_score', models.FloatField(blank=True, null=True)),
                ('ml_score', models.FloatField(blank=True, null=True)),
                ('triggered_rules', models.JSONField(blank=True, default=list)),
                ('reviewed_by', models.UUIDField(blank=True, null=True)),
                ('review_decision', models.CharField(blank=True, max_length=20, null=True)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
